name: WaterBoots
main: HTTPS7Team\WaterBoots\Main
version: 1.1.3
api:
 - 3.0.0-ALPHA5
 - 3.0.0-ALPHA6
 - 3.0.0-ALPHA7
 - 3.0.0-ALPHA8
 - 3.0.0-ALPHA9
 - 3.0.0-ALPHA10
 - 3.0.0-ALPHA11
load: POSTWORLD
author: HTTPS7Team
commands:
  waterboots:
   description: makes water spawn on you on sneaking!
  usage: "/wb"
  permission: boots.water
permissions:
  waterboots:
    default: false
    children:
      boots.water:
        default: op
        description: "Gives you perms to run the command"
